[project]
name = "quantapuzzle"
version = "0.1.0"
description = "Solves the Quanta Puzzle"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.9.1",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
    "ruff>=0.8.4",
]
